<?= $this->extend('layouts/dashboard') ?>
<?= $this->section('content') ?>
<?= view('components/page_header', ['title' => 'Payments & escrow', 'actions' => '<a class="btn btn-sm btn-light" href="' . site_url('admin/webhooks') . '">Webhook events</a><a class="btn btn-sm btn-light" href="' . site_url('admin/invoices') . '">Invoices</a>']) ?>
<div class="row g-3 mb-4">
    <?php foreach ($gateways as $code => $g): ?><div class="col-md-4"><div class="bc-card p-3 h-100"><div class="d-flex justify-content-between"><strong><?= esc($g->label()) ?></strong><?= $g->isAvailable() ? status_badge('active', 'Enabled') : status_badge('neutral', 'Disabled') ?></div><div class="small text-muted mt-1"><?= $g->isLive() ? 'Live — real money' : 'Sandbox — no money moves' ?> · escrow <?= $g->supportsEscrow() ? 'supported' : 'not supported' ?></div></div></div><?php endforeach ?>
    <div class="col-md-4"><div class="bc-card p-3 h-100"><div class="d-flex justify-content-between"><strong>Escrow partner</strong><?= $escrowProvider === 'none' ? pending_badge('Partner not selected') : status_badge('active', $escrowProvider) ?></div><div class="small text-muted mt-1">BearingCave never holds funds itself. Integrate a licensed escrow/payment provider via <span class="part-no">PaymentGatewayInterface</span>.</div></div></div>
</div>
<div class="bc-card"><?php if (! $rows): ?><?= empty_state('bi-credit-card', 'No payments recorded') ?><?php else: ?><div class="table-responsive"><table class="table table-bc table-stack mb-0"><thead><tr><th>Date</th><th>Company</th><th>Provider</th><th>Reference</th><th>Invoice</th><th class="text-end">Amount</th><th>Status</th></tr></thead><tbody>
<?php foreach ($rows as $p): ?><tr><td data-label="Date" class="small"><?= fdt($p['paid_at'] ?? $p['created_at']) ?></td><td data-label="Company" class="small"><?= esc($p['legal_name']) ?></td><td data-label="Provider"><?= esc($p['provider']) ?><?= $p['is_sandbox'] ? ' <span class="badge-sample">SANDBOX</span>' : '' ?></td><td data-label="Reference" class="part-no small"><?= esc($p['provider_reference'] ?? '—') ?></td><td data-label="Invoice"><?= $p['invoice_id'] ? '<a href="' . site_url('admin/invoices/' . $p['invoice_id']) . '">#' . (int) $p['invoice_id'] . '</a>' : '—' ?></td><td data-label="Amount" class="text-end"><?= money($p['amount'], $p['currency']) ?></td><td data-label="Status"><?= status_badge($p['status']) ?></td></tr><?php endforeach ?>
</tbody></table></div><?= $pager->links() ?><?php endif ?></div>
<?= $this->endSection() ?>
