<?= $this->extend('layouts/dashboard') ?>
<?= $this->section('content') ?>
<?= view('components/page_header', ['title' => 'Performance scores', 'subtitle' => 'Computed only from stored orders, shipments, inspections, RFQ responses and disputes. Empty means not enough data.', 'actions' => auth()->user()->can('performance.manage') ? post_button('admin/performance/recompute', 'Recalculate all', 'btn btn-sm btn-primary') : '']) ?>
<div class="bc-card mb-4"><div class="bc-card-header"><h2>Suppliers (by ranking)</h2></div><div class="table-responsive"><table class="table table-bc mb-0 small"><thead><tr><th>Supplier</th><th class="text-end">Ranking</th><th class="text-end">Score</th><th class="text-end">On-time %</th><th class="text-end">Rejection %</th><th class="text-end">Cost</th><th class="text-end">Resp. h</th><th class="text-end">Resp. %</th><th class="text-end">Service</th><th class="text-end">Orders</th><th>Risk</th><th>Computed</th></tr></thead><tbody>
<?php $f = static fn ($v) => $v === null ? '<span class="text-muted">—</span>' : esc((string) $v); foreach ($suppliers as $s): ?><tr><td><a href="<?= site_url('admin/companies/' . $s['id']) ?>"><?= esc($s['legal_name']) ?></a> <?= sample_badge($s) ?></td><td class="text-end"><?= esc($s['ranking_score']) ?></td><td class="text-end fw-semibold"><?= $f($s['performance_score']) ?></td><td class="text-end"><?= $f($s['on_time_delivery_pct']) ?></td><td class="text-end"><?= $f($s['quality_rejection_pct']) ?></td><td class="text-end"><?= $f($s['cost_competitiveness']) ?></td><td class="text-end"><?= $f($s['avg_response_hours']) ?></td><td class="text-end"><?= $f($s['rfq_response_rate_pct']) ?></td><td class="text-end"><?= $f($s['service_level']) ?></td><td class="text-end"><?= $f($s['orders_count']) ?></td><td><?= $s['risk_level'] ? status_badge($s['risk_level']) : '—' ?></td><td><?= fdate($s['computed_at']) ?></td></tr><?php endforeach ?>
</tbody></table></div></div>
<div class="bc-card"><div class="bc-card-header"><h2>Buyers (engagement)</h2></div><div class="table-responsive"><table class="table table-bc mb-0 small"><thead><tr><th>Buyer</th><th>Verification</th><th class="text-end">Engagement</th><th class="text-end">RFQ genuineness</th><th class="text-end">Transactions</th><th>Computed</th></tr></thead><tbody>
<?php foreach ($buyers as $b): ?><tr><td><a href="<?= site_url('admin/companies/' . $b['id']) ?>"><?= esc($b['legal_name']) ?></a></td><td><?= status_badge($b['verification_status']) ?></td><td class="text-end"><?= esc($b['engagement_score']) ?></td><td class="text-end"><?= esc($b['rfq_genuineness_score']) ?></td><td class="text-end"><?= esc($b['transaction_score']) ?></td><td><?= fdate($b['scores_computed_at']) ?></td></tr><?php endforeach ?>
</tbody></table></div></div>
<?= $this->endSection() ?>
