<?= $this->extend('layouts/dashboard') ?>
<?= $this->section('content') ?>
<?= view('components/page_header', ['title' => 'Supplier subscriptions', 'actions' => post_button('admin/subscriptions/run', 'Run expiry & reminders now', 'btn btn-sm btn-light')]) ?>
<div class="d-flex flex-wrap gap-2 mb-3"><?php foreach (['' => 'All', 'pending_payment' => 'Pending payment', 'active' => 'Active', 'expired' => 'Expired', 'cancelled' => 'Cancelled'] as $k => $l): ?><a class="btn btn-sm <?= (string) service('request')->getGet('status') === $k ? 'btn-primary' : 'btn-light' ?>" href="<?= site_url('admin/subscriptions?status=' . $k) ?>"><?= $l ?></a><?php endforeach ?><a class="btn btn-sm btn-light" href="<?= site_url('admin/subscriptions?expiring=1') ?>">Expiring ≤30 days</a></div>
<div class="bc-card"><?php if (! $rows): ?><?= empty_state('bi-calendar', 'No subscriptions') ?><?php else: ?><div class="table-responsive"><table class="table table-bc table-stack mb-0"><thead><tr><th>Company</th><th>Plan</th><th>Starts</th><th>Ends</th><th>Status</th><th>Invoice</th><th></th></tr></thead><tbody>
<?php foreach ($rows as $s): ?><tr><td data-label="Company"><a href="<?= site_url('admin/companies/' . $s['company_id']) ?>"><?= esc($s['legal_name']) ?></a> <?= sample_badge($s) ?></td><td data-label="Plan"><?= esc($s['plan_name']) ?></td><td data-label="Starts"><?= fdate($s['starts_on']) ?></td><td data-label="Ends"><?= fdate($s['ends_on']) ?></td><td data-label="Status"><?= status_badge($s['status']) ?></td><td data-label="Invoice"><?= $s['invoice_id'] ? '<a href="' . site_url('admin/invoices/' . $s['invoice_id']) . '">View</a>' : '—' ?></td>
<td><?php if (in_array($s['status'], ['pending_payment', 'active'], true)): ?><form method="post" action="<?= site_url('admin/subscriptions/' . $s['id'] . '/cancel') ?>" class="d-flex gap-1" data-confirm="Cancel this subscription?"><?= csrf_field() ?><input class="form-control form-control-sm" name="reason" placeholder="Reason" aria-label="Reason" style="max-width:140px"><button class="btn btn-sm btn-outline-danger" type="submit">Cancel</button></form><?php endif ?></td></tr><?php endforeach ?>
</tbody></table></div><?= $pager->links() ?><?php endif ?></div>
<?= $this->endSection() ?>
