-- =============================================================================
--  QMS - dedicated MySQL accounts (run ONCE as a DBA; never as the application)
-- =============================================================================
--  qms_app       Runtime account used by PHP-FPM. DML only: no DDL, no access to
--                other schemas, no DELETE on reports, append-only on evidence
--                tables (audit_logs, login_logs, inspection_approvals,
--                gauge_calibrations, user_password_history).
--  qms_migrator  Deployment account used only by `php spark migrate` during a
--                release. Keep it locked between releases:
--                  ALTER USER 'qms_migrator'@'localhost' ACCOUNT LOCK;   -- after deploy
--                  ALTER USER 'qms_migrator'@'localhost' ACCOUNT UNLOCK; -- before deploy
--  qms_backup    Read-only account for mysqldump (see deploy/backup).
--
--  Passwords are generated by MySQL (IDENTIFIED BY RANDOM PASSWORD, 8.0.18+)
--  and shown ONCE in the result set. Put them in the server-side environment
--  (PHP-FPM pool env / .env outside the web root, mode 0640) or a secret store.
--  Never commit them.
--
--  'localhost' = unix socket on the same host (preferred). If MySQL runs on a
--  separate host, use the application server's IP instead of localhost and
--  append REQUIRE SSL to every CREATE USER.
-- =============================================================================

CREATE DATABASE IF NOT EXISTS qms CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE USER 'qms_app'@'localhost'      IDENTIFIED BY RANDOM PASSWORD;
CREATE USER 'qms_migrator'@'localhost' IDENTIFIED BY RANDOM PASSWORD;
CREATE USER 'qms_backup'@'localhost'   IDENTIFIED BY RANDOM PASSWORD;

-- -----------------------------------------------------------------------------
-- Deployment account: owns schema objects (tables, indexes, triggers)
-- -----------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES, TRIGGER,
      CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, SHOW VIEW
   ON qms.* TO 'qms_migrator'@'localhost';

-- -----------------------------------------------------------------------------
-- Application runtime account
-- -----------------------------------------------------------------------------
-- Read access to the whole schema
GRANT SELECT ON qms.* TO 'qms_app'@'localhost';

-- Full DML where rows legitimately disappear (sessions, replay keys, matrix and
-- mapping edits, draft templates, draft inspection rows). Draft-only rules for
-- templates and inspections are additionally enforced by triggers.
GRANT INSERT, UPDATE, DELETE ON qms.ci_sessions             TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE, DELETE ON qms.idempotency_keys        TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE, DELETE ON qms.roles                   TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE, DELETE ON qms.role_permissions        TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE, DELETE ON qms.inspection_templates    TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE, DELETE ON qms.template_sections       TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE, DELETE ON qms.template_parameters     TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE, DELETE ON qms.template_part_map       TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE, DELETE ON qms.template_machine_map    TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE, DELETE ON qms.inspection_rounds       TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE, DELETE ON qms.inspection_observations TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE, DELETE ON qms.inspection_readings     TO 'qms_app'@'localhost';

-- Insert/update but never delete (master data is retired with is_active = 0;
-- reports are cancelled, never deleted)
GRANT INSERT, UPDATE ON qms.departments            TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE ON qms.employees              TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE ON qms.users                  TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE ON qms.shifts                 TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE ON qms.units                  TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE ON qms.inspection_methods     TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE ON qms.gauge_types            TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE ON qms.machines               TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE ON qms.parts                  TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE ON qms.gauges                 TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE ON qms.inspection_parameters  TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE ON qms.document_sequences     TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE ON qms.inspection_reports     TO 'qms_app'@'localhost';
GRANT INSERT, UPDATE ON qms.google_sheet_sync_logs TO 'qms_app'@'localhost';

-- Update only (rows are created by migrations)
GRANT UPDATE ON qms.system_settings TO 'qms_app'@'localhost';
GRANT UPDATE ON qms.report_types    TO 'qms_app'@'localhost';

-- Append-only evidence
GRANT INSERT ON qms.audit_logs            TO 'qms_app'@'localhost';
GRANT INSERT ON qms.login_logs            TO 'qms_app'@'localhost';
GRANT INSERT ON qms.inspection_approvals  TO 'qms_app'@'localhost';
GRANT INSERT ON qms.gauge_calibrations    TO 'qms_app'@'localhost';
GRANT INSERT ON qms.user_password_history TO 'qms_app'@'localhost';

-- -----------------------------------------------------------------------------
-- Backup account (mysqldump --single-transaction --source-data=2 --triggers)
-- RELOAD + REPLICATION CLIENT are only needed to record binlog coordinates for
-- point-in-time recovery; drop them if you do not use --source-data.
-- -----------------------------------------------------------------------------
GRANT SELECT, SHOW VIEW, TRIGGER, LOCK TABLES ON qms.* TO 'qms_backup'@'localhost';
GRANT RELOAD, REPLICATION CLIENT ON *.* TO 'qms_backup'@'localhost';
