<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

/**
 * Inspection reports, rounds, observations, readings, signatures, replay keys (module M8).
 *
 * Generated from database/schema/qms_schema.sql (the reviewed reference schema).
 * Raw SQL is used because CHECK constraints, generated columns, composite foreign
 * keys and triggers cannot be expressed with Forge. tests/database/SchemaParityTest
 * fails if the migrated schema ever differs from the reference file.
 */
class CreateInspectionTables extends Migration
{
    /** Tables owned by this migration, in creation order. */
    private const TABLES = ['inspection_reports', 'inspection_rounds', 'inspection_observations', 'inspection_readings', 'inspection_approvals', 'idempotency_keys'];

    /** DDL in execution order (tables, then the integrity triggers of each table). */
    private const STATEMENTS = [
        // inspection_reports
        <<<'SQL'
CREATE TABLE inspection_reports (
  id                    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  client_uuid           CHAR(36)     NOT NULL COMMENT 'Generated by the tablet when the inspection starts; makes creation idempotent',
  report_no             VARCHAR(30)  NULL COMMENT 'Allocated at first submission, e.g. SCA-2026-10-000001',
  revision_no           TINYINT UNSIGNED NOT NULL DEFAULT 0,
  parent_report_id      BIGINT UNSIGNED NULL COMMENT 'The revision this one corrects',
  revision_reason       VARCHAR(500) NULL,
  is_current            BOOLEAN      NOT NULL DEFAULT 1 COMMENT 'The revision that represents this report number in dashboards',
  report_type_id        INT UNSIGNED NOT NULL,
  template_id           INT UNSIGNED NOT NULL COMMENT 'Exact template version used',
  part_id               INT UNSIGNED NOT NULL,
  machine_id            INT UNSIGNED NOT NULL,
  shift_id              INT UNSIGNED NULL COMMENT 'Header shift; NULL for SHIFT_GRID reports (shift per round)',
  inspection_date       DATE         NOT NULL COMMENT 'Production date',
  received_at           DATETIME     NULL COMMENT 'Received time (Setup Change Approval)',
  finish_at             DATETIME     NULL COMMENT 'Finish time (Setup Change Approval)',
  operator_employee_id  INT UNSIGNED NULL,
  setter_employee_id    INT UNSIGNED NULL,
  status                ENUM('DRAFT','PENDING_PRODUCTION','PENDING_QUALITY','PENDING_QA','QA_APPROVED',
                             'RETURNED','REJECTED','CANCELLED','SUPERSEDED') NOT NULL DEFAULT 'DRAFT',
  overall_result        ENUM('PASS','FAIL','INCOMPLETE') NULL COMMENT 'Computed server-side',
  oos_count             SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Number of out-of-specification readings',
  remarks               VARCHAR(1000) NULL,
  submitted_at          DATETIME     NULL,
  submitted_by          INT UNSIGNED NULL,
  approved_at           DATETIME     NULL COMMENT 'Final QA approval',
  approved_by           INT UNSIGNED NULL,
  lock_version          INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Optimistic locking for concurrent tablets',
  created_at            DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by            INT UNSIGNED NOT NULL,
  updated_at            DATETIME     NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  updated_by            INT UNSIGNED NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_inspection_reports_client_uuid (client_uuid),
  UNIQUE KEY uq_inspection_reports_no_rev (report_no, revision_no),
  KEY idx_inspection_reports_date (inspection_date),
  KEY idx_inspection_reports_current_date (is_current, inspection_date),
  KEY idx_inspection_reports_type_date (report_type_id, inspection_date),
  KEY idx_inspection_reports_template (template_id, report_type_id),
  KEY idx_inspection_reports_part_date (part_id, inspection_date),
  KEY idx_inspection_reports_machine_date (machine_id, inspection_date),
  KEY idx_inspection_reports_shift_date (shift_id, inspection_date),
  KEY idx_inspection_reports_operator_date (operator_employee_id, inspection_date),
  KEY idx_inspection_reports_setter (setter_employee_id),
  KEY idx_inspection_reports_status_date (status, inspection_date),
  KEY idx_inspection_reports_creator_status (created_by, status),
  KEY idx_inspection_reports_submitter_date (submitted_by, inspection_date),
  KEY idx_inspection_reports_approver (approved_by),
  KEY idx_inspection_reports_parent (parent_report_id),
  CONSTRAINT fk_inspection_reports_type FOREIGN KEY (report_type_id) REFERENCES report_types (id),
  CONSTRAINT fk_inspection_reports_template FOREIGN KEY (template_id, report_type_id)
             REFERENCES inspection_templates (id, report_type_id),
  CONSTRAINT fk_inspection_reports_part FOREIGN KEY (part_id) REFERENCES parts (id),
  CONSTRAINT fk_inspection_reports_machine FOREIGN KEY (machine_id) REFERENCES machines (id),
  CONSTRAINT fk_inspection_reports_shift FOREIGN KEY (shift_id) REFERENCES shifts (id),
  CONSTRAINT fk_inspection_reports_operator FOREIGN KEY (operator_employee_id) REFERENCES employees (id),
  CONSTRAINT fk_inspection_reports_setter FOREIGN KEY (setter_employee_id) REFERENCES employees (id),
  CONSTRAINT fk_inspection_reports_submitted_by FOREIGN KEY (submitted_by) REFERENCES users (id),
  CONSTRAINT fk_inspection_reports_approved_by FOREIGN KEY (approved_by) REFERENCES users (id),
  CONSTRAINT fk_inspection_reports_created_by FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT fk_inspection_reports_parent FOREIGN KEY (parent_report_id) REFERENCES inspection_reports (id),
  CONSTRAINT chk_inspection_reports_revision CHECK ((revision_no = 0 AND parent_report_id IS NULL)
                                                   OR (revision_no > 0 AND parent_report_id IS NOT NULL
                                                       AND revision_reason IS NOT NULL)),
  CONSTRAINT chk_inspection_reports_number CHECK (status IN ('DRAFT','CANCELLED') OR report_no IS NOT NULL),
  CONSTRAINT chk_inspection_reports_submitted CHECK (status IN ('DRAFT','CANCELLED')
                                                    OR (submitted_at IS NOT NULL AND submitted_by IS NOT NULL)),
  CONSTRAINT chk_inspection_reports_approved CHECK (status NOT IN ('QA_APPROVED','SUPERSEDED')
                                                   OR (approved_at IS NOT NULL AND approved_by IS NOT NULL)),
  CONSTRAINT chk_inspection_reports_superseded CHECK (status <> 'SUPERSEDED' OR is_current = 0),
  CONSTRAINT chk_inspection_reports_timing CHECK (finish_at IS NULL OR received_at IS NULL OR finish_at >= received_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='Inspection report header. Data is frozen once submitted; approved reports change only via revisions'
SQL,
        // trg_inspection_reports_lock
        <<<'SQL'
CREATE TRIGGER trg_inspection_reports_lock BEFORE UPDATE ON inspection_reports FOR EACH ROW
BEGIN
  IF OLD.status NOT IN ('DRAFT','RETURNED') THEN
    IF NOT (NEW.id <=> OLD.id AND NEW.client_uuid <=> OLD.client_uuid
            AND NEW.report_no <=> OLD.report_no AND NEW.revision_no <=> OLD.revision_no
            AND NEW.parent_report_id <=> OLD.parent_report_id AND NEW.revision_reason <=> OLD.revision_reason
            AND NEW.report_type_id <=> OLD.report_type_id AND NEW.template_id <=> OLD.template_id
            AND NEW.part_id <=> OLD.part_id AND NEW.machine_id <=> OLD.machine_id
            AND NEW.shift_id <=> OLD.shift_id AND NEW.inspection_date <=> OLD.inspection_date
            AND NEW.received_at <=> OLD.received_at AND NEW.finish_at <=> OLD.finish_at
            AND NEW.operator_employee_id <=> OLD.operator_employee_id
            AND NEW.setter_employee_id <=> OLD.setter_employee_id
            AND NEW.overall_result <=> OLD.overall_result AND NEW.oos_count <=> OLD.oos_count
            AND NEW.remarks <=> OLD.remarks AND NEW.submitted_at <=> OLD.submitted_at
            AND NEW.submitted_by <=> OLD.submitted_by
            AND NEW.created_at <=> OLD.created_at AND NEW.created_by <=> OLD.created_by) THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'QMS-LOCK: inspection data is read-only after submission';
    END IF;
    IF OLD.status IN ('QA_APPROVED','REJECTED','CANCELLED','SUPERSEDED')
       AND NOT (OLD.status = 'QA_APPROVED' AND NEW.status = 'SUPERSEDED' AND NEW.is_current = 0
                AND NEW.approved_at <=> OLD.approved_at AND NEW.approved_by <=> OLD.approved_by) THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'QMS-LOCK: finalised inspection report is read-only';
    END IF;
  END IF;
END
SQL,
        // trg_inspection_reports_no_delete
        <<<'SQL'
CREATE TRIGGER trg_inspection_reports_no_delete BEFORE DELETE ON inspection_reports FOR EACH ROW
BEGIN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'QMS-LOCK: inspection reports cannot be deleted (cancel instead)';
END
SQL,
        // inspection_rounds
        <<<'SQL'
CREATE TABLE inspection_rounds (
  id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  report_id           BIGINT UNSIGNED NOT NULL,
  round_no            SMALLINT UNSIGNED NOT NULL COMMENT 'Single-round layouts always have exactly round 1',
  shift_id            INT UNSIGNED NULL COMMENT 'SHIFT_GRID only (Shift A / B / C)',
  inspection_time     TIME         NULL COMMENT 'SHIFT_GRID only: time of this inspection',
  status              ENUM('OPEN','SIGNED','VERIFIED') NOT NULL DEFAULT 'OPEN',
  lot_status          ENUM('ACCEPTED','REJECTED','REWORK','ON_HOLD') NULL,
  accepted_qty        INT UNSIGNED NULL,
  rejected_qty        INT UNSIGNED NULL,
  rework_qty          INT UNSIGNED NULL,
  operator_user_id    INT UNSIGNED NULL COMMENT 'Inspected By Operator (e-signature)',
  operator_signed_at  DATETIME     NULL,
  qe_user_id          INT UNSIGNED NULL COMMENT 'Inspected By Quality Engineer (e-signature)',
  qe_verified_at      DATETIME     NULL,
  remarks             VARCHAR(500) NULL,
  created_at          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by          INT UNSIGNED NULL,
  updated_at          DATETIME     NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  updated_by          INT UNSIGNED NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_inspection_rounds_no (report_id, round_no),
  UNIQUE KEY uq_inspection_rounds_id_report (id, report_id),
  KEY idx_inspection_rounds_shift (shift_id),
  KEY idx_inspection_rounds_operator (operator_user_id, operator_signed_at),
  KEY idx_inspection_rounds_qe (qe_user_id),
  CONSTRAINT fk_inspection_rounds_report FOREIGN KEY (report_id) REFERENCES inspection_reports (id) ON DELETE CASCADE,
  CONSTRAINT fk_inspection_rounds_shift FOREIGN KEY (shift_id) REFERENCES shifts (id),
  CONSTRAINT fk_inspection_rounds_operator FOREIGN KEY (operator_user_id) REFERENCES users (id),
  CONSTRAINT fk_inspection_rounds_qe FOREIGN KEY (qe_user_id) REFERENCES users (id),
  CONSTRAINT chk_inspection_rounds_signed CHECK (status = 'OPEN'
                                                OR (operator_user_id IS NOT NULL AND operator_signed_at IS NOT NULL)),
  CONSTRAINT chk_inspection_rounds_verified CHECK ((status = 'VERIFIED') = (qe_user_id IS NOT NULL AND qe_verified_at IS NOT NULL)),
  CONSTRAINT chk_inspection_rounds_distinct CHECK (qe_user_id IS NULL OR operator_user_id IS NULL OR qe_user_id <> operator_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='Inspection rounds: one per report for single layouts, one per shift/inspection time for SHIFT_GRID'
SQL,
        // trg_inspection_rounds_bi
        <<<'SQL'
CREATE TRIGGER trg_inspection_rounds_bi BEFORE INSERT ON inspection_rounds FOR EACH ROW
BEGIN
  IF (SELECT status FROM inspection_reports WHERE id = NEW.report_id) NOT IN ('DRAFT','RETURNED') THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'QMS-LOCK: report is not editable';
  END IF;
END
SQL,
        // trg_inspection_rounds_bu
        <<<'SQL'
CREATE TRIGGER trg_inspection_rounds_bu BEFORE UPDATE ON inspection_rounds FOR EACH ROW
BEGIN
  IF (SELECT status FROM inspection_reports WHERE id = OLD.report_id) NOT IN ('DRAFT','RETURNED')
     OR NOT (NEW.report_id <=> OLD.report_id) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'QMS-LOCK: report is not editable';
  END IF;
END
SQL,
        // trg_inspection_rounds_bd
        <<<'SQL'
CREATE TRIGGER trg_inspection_rounds_bd BEFORE DELETE ON inspection_rounds FOR EACH ROW
BEGIN
  IF (SELECT status FROM inspection_reports WHERE id = OLD.report_id) NOT IN ('DRAFT','RETURNED') THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'QMS-LOCK: report is not editable';
  END IF;
END
SQL,
        // inspection_observations
        <<<'SQL'
CREATE TABLE inspection_observations (
  id                     BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  report_id              BIGINT UNSIGNED NOT NULL,
  round_id               BIGINT UNSIGNED NOT NULL,
  template_parameter_id  INT UNSIGNED NOT NULL,
  lsl                    DECIMAL(18,6) NULL COMMENT 'Specification snapshot copied server-side from the template',
  usl                    DECIMAL(18,6) NULL,
  gauge_id               INT UNSIGNED NULL COMMENT 'Gauge ID used',
  gauge_cal_due_date     DATE         NULL COMMENT 'Calibration due date of the gauge when it was used',
  gauge_cal_valid        BOOLEAN      NULL COMMENT '1 = gauge was ACTIVE and in calibration on the inspection date',
  result                 ENUM('PASS','FAIL','INCOMPLETE','NOT_APPLICABLE') NOT NULL DEFAULT 'INCOMPLETE',
  remarks                VARCHAR(500) NULL,
  created_at             DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by             INT UNSIGNED NULL,
  updated_at             DATETIME     NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  updated_by             INT UNSIGNED NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_inspection_observations_param (round_id, template_parameter_id),
  KEY idx_inspection_observations_round_report (round_id, report_id),
  KEY idx_inspection_observations_report_result (report_id, result),
  KEY idx_inspection_observations_parameter (template_parameter_id),
  KEY idx_inspection_observations_gauge (gauge_id),
  CONSTRAINT fk_inspection_observations_report FOREIGN KEY (report_id) REFERENCES inspection_reports (id) ON DELETE CASCADE,
  CONSTRAINT fk_inspection_observations_round FOREIGN KEY (round_id, report_id)
             REFERENCES inspection_rounds (id, report_id) ON DELETE CASCADE,
  CONSTRAINT fk_inspection_observations_parameter FOREIGN KEY (template_parameter_id) REFERENCES template_parameters (id),
  CONSTRAINT fk_inspection_observations_gauge FOREIGN KEY (gauge_id) REFERENCES gauges (id),
  CONSTRAINT chk_inspection_observations_limits CHECK (lsl IS NULL OR usl IS NULL OR lsl <= usl),
  CONSTRAINT chk_inspection_observations_gauge CHECK ((gauge_id IS NULL) = (gauge_cal_valid IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='One row per parameter per round: gauge used, remarks, spec snapshot and aggregated result'
SQL,
        // trg_inspection_observations_bi
        <<<'SQL'
CREATE TRIGGER trg_inspection_observations_bi BEFORE INSERT ON inspection_observations FOR EACH ROW
BEGIN
  IF (SELECT status FROM inspection_reports WHERE id = NEW.report_id) NOT IN ('DRAFT','RETURNED') THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'QMS-LOCK: report is not editable';
  END IF;
END
SQL,
        // trg_inspection_observations_bu
        <<<'SQL'
CREATE TRIGGER trg_inspection_observations_bu BEFORE UPDATE ON inspection_observations FOR EACH ROW
BEGIN
  IF (SELECT status FROM inspection_reports WHERE id = OLD.report_id) NOT IN ('DRAFT','RETURNED')
     OR NOT (NEW.report_id <=> OLD.report_id) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'QMS-LOCK: report is not editable';
  END IF;
END
SQL,
        // trg_inspection_observations_bd
        <<<'SQL'
CREATE TRIGGER trg_inspection_observations_bd BEFORE DELETE ON inspection_observations FOR EACH ROW
BEGIN
  IF (SELECT status FROM inspection_reports WHERE id = OLD.report_id) NOT IN ('DRAFT','RETURNED') THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'QMS-LOCK: report is not editable';
  END IF;
END
SQL,
        // inspection_readings
        <<<'SQL'
CREATE TABLE inspection_readings (
  id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  observation_id  BIGINT UNSIGNED NOT NULL,
  reading_no      TINYINT UNSIGNED NOT NULL COMMENT 'Observation 1, Observation 2 ...',
  value_numeric   DECIMAL(18,6) NULL COMMENT 'NUMERIC and PERCENTAGE',
  value_choice    ENUM('OK','NOT_OK','GO','NO_GO') NULL COMMENT 'OK_NOT_OK, VISUAL and GO_NO_GO',
  value_text      VARCHAR(255) NULL COMMENT 'TEXT',
  value_date      DATE         NULL COMMENT 'DATE',
  value_time      TIME         NULL COMMENT 'TIME',
  result          ENUM('PASS','FAIL','NOT_APPLICABLE') NULL COMMENT 'Computed server-side; NULL while empty',
  created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by      INT UNSIGNED NULL,
  updated_at      DATETIME     NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  updated_by      INT UNSIGNED NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_inspection_readings_no (observation_id, reading_no),
  CONSTRAINT fk_inspection_readings_observation FOREIGN KEY (observation_id)
             REFERENCES inspection_observations (id) ON DELETE CASCADE,
  CONSTRAINT chk_inspection_readings_no CHECK (reading_no BETWEEN 1 AND 10),
  CONSTRAINT chk_inspection_readings_single_value CHECK ((value_numeric IS NOT NULL) + (value_choice IS NOT NULL)
                                                        + (value_text IS NOT NULL) + (value_date IS NOT NULL)
                                                        + (value_time IS NOT NULL) <= 1),
  CONSTRAINT chk_inspection_readings_result CHECK ((result IS NULL) = (value_numeric IS NULL AND value_choice IS NULL
                                                                      AND value_text IS NULL AND value_date IS NULL
                                                                      AND value_time IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='Individual readings with typed values and PASS/FAIL'
SQL,
        // trg_inspection_readings_bi
        <<<'SQL'
CREATE TRIGGER trg_inspection_readings_bi BEFORE INSERT ON inspection_readings FOR EACH ROW
BEGIN
  IF (SELECT r.status FROM inspection_observations o JOIN inspection_reports r ON r.id = o.report_id
      WHERE o.id = NEW.observation_id) NOT IN ('DRAFT','RETURNED') THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'QMS-LOCK: report is not editable';
  END IF;
END
SQL,
        // trg_inspection_readings_bu
        <<<'SQL'
CREATE TRIGGER trg_inspection_readings_bu BEFORE UPDATE ON inspection_readings FOR EACH ROW
BEGIN
  IF (SELECT r.status FROM inspection_observations o JOIN inspection_reports r ON r.id = o.report_id
      WHERE o.id = OLD.observation_id) NOT IN ('DRAFT','RETURNED')
     OR NOT (NEW.observation_id <=> OLD.observation_id) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'QMS-LOCK: report is not editable';
  END IF;
END
SQL,
        // trg_inspection_readings_bd
        <<<'SQL'
CREATE TRIGGER trg_inspection_readings_bd BEFORE DELETE ON inspection_readings FOR EACH ROW
BEGIN
  IF (SELECT r.status FROM inspection_observations o JOIN inspection_reports r ON r.id = o.report_id
      WHERE o.id = OLD.observation_id) NOT IN ('DRAFT','RETURNED') THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'QMS-LOCK: report is not editable';
  END IF;
END
SQL,
        // inspection_approvals
        <<<'SQL'
CREATE TABLE inspection_approvals (
  id               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  report_id        BIGINT UNSIGNED NOT NULL,
  stage            ENUM('SUBMISSION','PRODUCTION_VERIFICATION','QUALITY_VERIFICATION','QA_APPROVAL',
                        'REVISION','CANCELLATION') NOT NULL,
  action           ENUM('SUBMITTED','APPROVED','RETURNED','REJECTED','CANCELLED','REVISION_CREATED','SUPERSEDED') NOT NULL,
  from_status      ENUM('DRAFT','PENDING_PRODUCTION','PENDING_QUALITY','PENDING_QA','QA_APPROVED',
                        'RETURNED','REJECTED','CANCELLED','SUPERSEDED') NOT NULL,
  to_status        ENUM('DRAFT','PENDING_PRODUCTION','PENDING_QUALITY','PENDING_QA','QA_APPROVED',
                        'RETURNED','REJECTED','CANCELLED','SUPERSEDED') NOT NULL,
  user_id          INT UNSIGNED NOT NULL COMMENT 'Signer',
  role_id          INT UNSIGNED NOT NULL COMMENT 'Role held when signing = meaning of the signature',
  remarks          VARCHAR(1000) NULL,
  reauthenticated  BOOLEAN      NOT NULL DEFAULT 0 COMMENT 'Signer re-entered the password for this signature',
  ip_address       VARCHAR(45)  NULL,
  signed_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_inspection_approvals_report (report_id, signed_at),
  KEY idx_inspection_approvals_user (user_id, signed_at),
  KEY idx_inspection_approvals_role (role_id),
  CONSTRAINT fk_inspection_approvals_report FOREIGN KEY (report_id) REFERENCES inspection_reports (id),
  CONSTRAINT fk_inspection_approvals_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_inspection_approvals_role FOREIGN KEY (role_id) REFERENCES roles (id),
  CONSTRAINT chk_inspection_approvals_remarks CHECK (action NOT IN ('RETURNED','REJECTED','CANCELLED','REVISION_CREATED')
                                                    OR remarks IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='Append-only workflow signatures (who, what stage, when, why)'
SQL,
        // trg_inspection_approvals_no_update
        <<<'SQL'
CREATE TRIGGER trg_inspection_approvals_no_update BEFORE UPDATE ON inspection_approvals FOR EACH ROW
BEGIN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'QMS-LOCK: approval signatures are append-only';
END
SQL,
        // trg_inspection_approvals_no_delete
        <<<'SQL'
CREATE TRIGGER trg_inspection_approvals_no_delete BEFORE DELETE ON inspection_approvals FOR EACH ROW
BEGIN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'QMS-LOCK: approval signatures are append-only';
END
SQL,
        // idempotency_keys
        <<<'SQL'
CREATE TABLE idempotency_keys (
  id             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id        INT UNSIGNED NOT NULL,
  idem_key       CHAR(36)     NOT NULL COMMENT 'UUID generated by the browser per action attempt',
  action         VARCHAR(50)  NOT NULL,
  request_hash   CHAR(64)     NOT NULL COMMENT 'SHA-256 of the request payload; same key + different payload is rejected',
  response_code  SMALLINT UNSIGNED NULL,
  response_body  JSON         NULL,
  created_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_idempotency_keys_user_key (user_id, idem_key),
  KEY idx_idempotency_keys_created (created_at),
  CONSTRAINT fk_idempotency_keys_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='Replay protection for submit / approve requests (purged after 48 h)'
SQL,
    ];

    public function up(): void
    {
        foreach (self::STATEMENTS as $statement) {
            $this->db->query($statement);
        }
    }

    public function down(): void
    {
        // Dropping a table also drops its triggers.
        foreach (array_reverse(self::TABLES) as $table) {
            $this->db->query('DROP TABLE IF EXISTS `' . $table . '`');
        }
    }
}
